name: $(Date:yyyyMMdd).$(Rev:r)

variables:
  - name: imageName
    value: 'pipelines-golang-docker'

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
     - doc
     - ReadME.md

stages:
- stage: Build
  variables:
  - group: TechChallengeApp
  jobs:
  - job: 'Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: 'Replace Secure Credential Value in TOML file'
      inputs:
          rootDirectory: '$(Build.Repository.LocalPath)'
          targetFiles: '**/conf.toml'
    - task: ShellScript@2
      displayName: Build Solution
      inputs:
        scriptPath: '$(Build.Repository.LocalPath)/build.sh'
        failOnStandardError: false
    - task: Docker@2
      displayName: Build and Push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageName)
        Dockerfile: '$(Build.Repository.LocalPath)/Dockerfile'
        containerRegistry: acrServiceConnection
    - publish: $(Build.Repository.LocalPath)/dist
      artifact: drop

- stage: Deploy
  variables:
  - group: TechChallengeApp
  jobs:
  - job: 'Deploy'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: drop
    - task: Bash@3
      displayName: Run DB Migration
      inputs:
        targetType: 'inline'
        script: sudo ./TechChallengeApp.exe updatedb
        workingDirectory: '$(Pipeline.Workspace)/drop'
        failOnStderr: false

