name: $(Date:yyyyMMdd).$(Rev:r)

variables:
  - group: TechChallengeApp
    imageName: 'pipelines-golang-docker'

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
     - doc
     - ReadME.md

stages:
- stage: Build
  variables:
  - group: TechChallengeApp
  jobs:
  - job: 'Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: ShellScript@2
      inputs:
        scriptPath: '$(Build.Repository.LocalPath)/build.sh'
        failOnStandardError: false
    - task: Docker@2
      displayName: Build and Push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageName)
        Dockerfile: '$(Build.Repository.LocalPath)/Dockerfile'
        containerRegistry: acrServiceConnection
    - publish: $(Build.Repository.LocalPath)/dist
      artifact: drop