apiVersion: apps/v1
kind: Deployment
metadata:
  name: TechChalangeApp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: TechChalangeApp
  template:
    metadata:
      labels:
        app: TechChalangeApp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: TechChalangeApp
        image: acrdemoanup.azurecr.io/pipelines-golang-docker:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: TechChalangeApp
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: TechChalangeApp